//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 03:36:58 AM WET 
//


package org.mobicents.slee.sippresence.pojo.pidf.oma.pde;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobicents.slee.sippresence.pojo.pidf.oma.pde package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Home_QNAME = new QName("urn:oma:xml:pde:pidf:ext", "home");
    private final static QName _Visited_QNAME = new QName("urn:oma:xml:pde:pidf:ext", "visited");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobicents.slee.sippresence.pojo.pidf.oma.pde
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SessionAnswermode }
     * 
     */
    public SessionAnswermode createSessionAnswermode() {
        return new SessionAnswermode();
    }

    /**
     * Create an instance of {@link EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmptyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oma:xml:pde:pidf:ext", name = "home")
    public JAXBElement<EmptyType> createHome(EmptyType value) {
        return new JAXBElement<EmptyType>(_Home_QNAME, EmptyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EmptyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oma:xml:pde:pidf:ext", name = "visited")
    public JAXBElement<EmptyType> createVisited(EmptyType value) {
        return new JAXBElement<EmptyType>(_Visited_QNAME, EmptyType.class, null, value);
    }

}
