//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 03:36:58 AM WET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oma:xml:pde:pidf:ext", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.mobicents.slee.sippresence.pojo.pidf.oma.pde;
