//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 03:36:58 AM WET 
//


package org.mobicents.slee.sippresence.pojo.pidf.uacaps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actortype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actortype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="supported" type="{urn:ietf:params:xml:ns:pidf:caps}actortypes" minOccurs="0"/>
 *         &lt;element name="notsupported" type="{urn:ietf:params:xml:ns:pidf:caps}actortypes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actortype", propOrder = {
    "supported",
    "notsupported"
})
public class Actortype {

    protected Actortypes supported;
    protected Actortypes notsupported;

    /**
     * Gets the value of the supported property.
     * 
     * @return
     *     possible object is
     *     {@link Actortypes }
     *     
     */
    public Actortypes getSupported() {
        return supported;
    }

    /**
     * Sets the value of the supported property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actortypes }
     *     
     */
    public void setSupported(Actortypes value) {
        this.supported = value;
    }

    /**
     * Gets the value of the notsupported property.
     * 
     * @return
     *     possible object is
     *     {@link Actortypes }
     *     
     */
    public Actortypes getNotsupported() {
        return notsupported;
    }

    /**
     * Sets the value of the notsupported property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actortypes }
     *     
     */
    public void setNotsupported(Actortypes value) {
        this.notsupported = value;
    }

}
