/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 03:36:58 AM WET 
//


package org.mobicents.slee.sippresence.pojo.pidf.uacaps;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for eventtypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="eventtypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dialog" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kpml" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="message-summary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="poc-settings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="presence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="refer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Siemens-RTP-Stats" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spirits-INDPs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="spirits-user-prof" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="winfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventtypes", propOrder = {
    "conference",
    "dialog",
    "kpml",
    "messageSummary",
    "pocSettings",
    "presence",
    "reg",
    "refer",
    "siemensRTPStats",
    "spiritsINDPs",
    "spiritsUserProf",
    "winfo",
    "any"
})
public class Eventtypes {

    protected String conference;
    protected String dialog;
    protected String kpml;
    @XmlElement(name = "message-summary")
    protected String messageSummary;
    @XmlElement(name = "poc-settings")
    protected String pocSettings;
    protected String presence;
    protected String reg;
    protected String refer;
    @XmlElement(name = "Siemens-RTP-Stats")
    protected String siemensRTPStats;
    @XmlElement(name = "spirits-INDPs")
    protected String spiritsINDPs;
    @XmlElement(name = "spirits-user-prof")
    protected String spiritsUserProf;
    protected String winfo;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the conference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConference() {
        return conference;
    }

    /**
     * Sets the value of the conference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConference(String value) {
        this.conference = value;
    }

    /**
     * Gets the value of the dialog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDialog() {
        return dialog;
    }

    /**
     * Sets the value of the dialog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDialog(String value) {
        this.dialog = value;
    }

    /**
     * Gets the value of the kpml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKpml() {
        return kpml;
    }

    /**
     * Sets the value of the kpml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKpml(String value) {
        this.kpml = value;
    }

    /**
     * Gets the value of the messageSummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageSummary() {
        return messageSummary;
    }

    /**
     * Sets the value of the messageSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageSummary(String value) {
        this.messageSummary = value;
    }

    /**
     * Gets the value of the pocSettings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPocSettings() {
        return pocSettings;
    }

    /**
     * Sets the value of the pocSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPocSettings(String value) {
        this.pocSettings = value;
    }

    /**
     * Gets the value of the presence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresence() {
        return presence;
    }

    /**
     * Sets the value of the presence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresence(String value) {
        this.presence = value;
    }

    /**
     * Gets the value of the reg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReg() {
        return reg;
    }

    /**
     * Sets the value of the reg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReg(String value) {
        this.reg = value;
    }

    /**
     * Gets the value of the refer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefer() {
        return refer;
    }

    /**
     * Sets the value of the refer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefer(String value) {
        this.refer = value;
    }

    /**
     * Gets the value of the siemensRTPStats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiemensRTPStats() {
        return siemensRTPStats;
    }

    /**
     * Sets the value of the siemensRTPStats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiemensRTPStats(String value) {
        this.siemensRTPStats = value;
    }

    /**
     * Gets the value of the spiritsINDPs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpiritsINDPs() {
        return spiritsINDPs;
    }

    /**
     * Sets the value of the spiritsINDPs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpiritsINDPs(String value) {
        this.spiritsINDPs = value;
    }

    /**
     * Gets the value of the spiritsUserProf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpiritsUserProf() {
        return spiritsUserProf;
    }

    /**
     * Sets the value of the spiritsUserProf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpiritsUserProf(String value) {
        this.spiritsUserProf = value;
    }

    /**
     * Gets the value of the winfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWinfo() {
        return winfo;
    }

    /**
     * Sets the value of the winfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWinfo(String value) {
        this.winfo = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
