/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 03:36:58 AM WET 
//


package org.mobicents.slee.sippresence.pojo.pidf.uacaps;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for extensiontypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="extensiontypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rel100" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="early-session" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eventlist" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="from-change" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gruu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hist-info" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="join" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="norefersub" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="precondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="privacy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recipient-list-invite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="recipient-list-subscribe" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="replaces" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resource-priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sdp-anat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sec-agree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tdialog" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="timer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "extensiontypes", propOrder = {
    "rel100",
    "earlySession",
    "eventlist",
    "fromChange",
    "gruu",
    "histInfo",
    "join",
    "norefersub",
    "path",
    "precondition",
    "pref",
    "privacy",
    "recipientListInvite",
    "recipientListSubscribe",
    "replaces",
    "resourcePriority",
    "sdpAnat",
    "secAgree",
    "tdialog",
    "timer",
    "any"
})
public class Extensiontypes {

    protected String rel100;
    @XmlElement(name = "early-session")
    protected String earlySession;
    protected String eventlist;
    @XmlElement(name = "from-change")
    protected String fromChange;
    protected String gruu;
    @XmlElement(name = "hist-info")
    protected String histInfo;
    protected String join;
    protected String norefersub;
    protected String path;
    protected String precondition;
    protected String pref;
    protected String privacy;
    @XmlElement(name = "recipient-list-invite")
    protected String recipientListInvite;
    @XmlElement(name = "recipient-list-subscribe")
    protected String recipientListSubscribe;
    protected String replaces;
    @XmlElement(name = "resource-priority")
    protected String resourcePriority;
    @XmlElement(name = "sdp-anat")
    protected String sdpAnat;
    @XmlElement(name = "sec-agree")
    protected String secAgree;
    protected String tdialog;
    protected String timer;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the rel100 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRel100() {
        return rel100;
    }

    /**
     * Sets the value of the rel100 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRel100(String value) {
        this.rel100 = value;
    }

    /**
     * Gets the value of the earlySession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarlySession() {
        return earlySession;
    }

    /**
     * Sets the value of the earlySession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarlySession(String value) {
        this.earlySession = value;
    }

    /**
     * Gets the value of the eventlist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventlist() {
        return eventlist;
    }

    /**
     * Sets the value of the eventlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventlist(String value) {
        this.eventlist = value;
    }

    /**
     * Gets the value of the fromChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromChange() {
        return fromChange;
    }

    /**
     * Sets the value of the fromChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromChange(String value) {
        this.fromChange = value;
    }

    /**
     * Gets the value of the gruu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGruu() {
        return gruu;
    }

    /**
     * Sets the value of the gruu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGruu(String value) {
        this.gruu = value;
    }

    /**
     * Gets the value of the histInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHistInfo() {
        return histInfo;
    }

    /**
     * Sets the value of the histInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHistInfo(String value) {
        this.histInfo = value;
    }

    /**
     * Gets the value of the join property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoin() {
        return join;
    }

    /**
     * Sets the value of the join property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoin(String value) {
        this.join = value;
    }

    /**
     * Gets the value of the norefersub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNorefersub() {
        return norefersub;
    }

    /**
     * Sets the value of the norefersub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNorefersub(String value) {
        this.norefersub = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the precondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecondition() {
        return precondition;
    }

    /**
     * Sets the value of the precondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecondition(String value) {
        this.precondition = value;
    }

    /**
     * Gets the value of the pref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPref() {
        return pref;
    }

    /**
     * Sets the value of the pref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPref(String value) {
        this.pref = value;
    }

    /**
     * Gets the value of the privacy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacy() {
        return privacy;
    }

    /**
     * Sets the value of the privacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacy(String value) {
        this.privacy = value;
    }

    /**
     * Gets the value of the recipientListInvite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientListInvite() {
        return recipientListInvite;
    }

    /**
     * Sets the value of the recipientListInvite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientListInvite(String value) {
        this.recipientListInvite = value;
    }

    /**
     * Gets the value of the recipientListSubscribe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientListSubscribe() {
        return recipientListSubscribe;
    }

    /**
     * Sets the value of the recipientListSubscribe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientListSubscribe(String value) {
        this.recipientListSubscribe = value;
    }

    /**
     * Gets the value of the replaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplaces() {
        return replaces;
    }

    /**
     * Sets the value of the replaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplaces(String value) {
        this.replaces = value;
    }

    /**
     * Gets the value of the resourcePriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourcePriority() {
        return resourcePriority;
    }

    /**
     * Sets the value of the resourcePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourcePriority(String value) {
        this.resourcePriority = value;
    }

    /**
     * Gets the value of the sdpAnat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSdpAnat() {
        return sdpAnat;
    }

    /**
     * Sets the value of the sdpAnat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSdpAnat(String value) {
        this.sdpAnat = value;
    }

    /**
     * Gets the value of the secAgree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecAgree() {
        return secAgree;
    }

    /**
     * Sets the value of the secAgree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecAgree(String value) {
        this.secAgree = value;
    }

    /**
     * Gets the value of the tdialog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdialog() {
        return tdialog;
    }

    /**
     * Sets the value of the tdialog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdialog(String value) {
        this.tdialog = value;
    }

    /**
     * Gets the value of the timer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimer() {
        return timer;
    }

    /**
     * Sets the value of the timer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimer(String value) {
        this.timer = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
