/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 03:36:58 AM WET 
//


package org.mobicents.slee.sippresence.pojo.pidf.uacaps;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mobicents.slee.sippresence.pojo.pidf.uacaps package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Servcaps_QNAME = new QName("urn:ietf:params:xml:ns:pidf:caps", "servcaps");
    private final static QName _Devcaps_QNAME = new QName("urn:ietf:params:xml:ns:pidf:caps", "devcaps");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mobicents.slee.sippresence.pojo.pidf.uacaps
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Eventtypes }
     * 
     */
    public Eventtypes createEventtypes() {
        return new Eventtypes();
    }

    /**
     * Create an instance of {@link Methodstype }
     * 
     */
    public Methodstype createMethodstype() {
        return new Methodstype();
    }

    /**
     * Create an instance of {@link Equalstype }
     * 
     */
    public Equalstype createEqualstype() {
        return new Equalstype();
    }

    /**
     * Create an instance of {@link Descriptiontype }
     * 
     */
    public Descriptiontype createDescriptiontype() {
        return new Descriptiontype();
    }

    /**
     * Create an instance of {@link Languagestype.Supported }
     * 
     */
    public Languagestype.Supported createLanguagestypeSupported() {
        return new Languagestype.Supported();
    }

    /**
     * Create an instance of {@link EventPackagestype }
     * 
     */
    public EventPackagestype createEventPackagestype() {
        return new EventPackagestype();
    }

    /**
     * Create an instance of {@link Prioritytypes }
     * 
     */
    public Prioritytypes createPrioritytypes() {
        return new Prioritytypes();
    }

    /**
     * Create an instance of {@link Extensionstype }
     * 
     */
    public Extensionstype createExtensionstype() {
        return new Extensionstype();
    }

    /**
     * Create an instance of {@link Mobilitytype }
     * 
     */
    public Mobilitytype createMobilitytype() {
        return new Mobilitytype();
    }

    /**
     * Create an instance of {@link Languagestype.Notsupported }
     * 
     */
    public Languagestype.Notsupported createLanguagestypeNotsupported() {
        return new Languagestype.Notsupported();
    }

    /**
     * Create an instance of {@link Rangetype }
     * 
     */
    public Rangetype createRangetype() {
        return new Rangetype();
    }

    /**
     * Create an instance of {@link Extensiontypes }
     * 
     */
    public Extensiontypes createExtensiontypes() {
        return new Extensiontypes();
    }

    /**
     * Create an instance of {@link Prioritytype }
     * 
     */
    public Prioritytype createPrioritytype() {
        return new Prioritytype();
    }

    /**
     * Create an instance of {@link Methodtypes }
     * 
     */
    public Methodtypes createMethodtypes() {
        return new Methodtypes();
    }

    /**
     * Create an instance of {@link Classtype }
     * 
     */
    public Classtype createClasstype() {
        return new Classtype();
    }

    /**
     * Create an instance of {@link Devcaps }
     * 
     */
    public Devcaps createDevcaps() {
        return new Devcaps();
    }

    /**
     * Create an instance of {@link Classtypes }
     * 
     */
    public Classtypes createClasstypes() {
        return new Classtypes();
    }

    /**
     * Create an instance of {@link Schemestype }
     * 
     */
    public Schemestype createSchemestype() {
        return new Schemestype();
    }

    /**
     * Create an instance of {@link Higherthantype }
     * 
     */
    public Higherthantype createHigherthantype() {
        return new Higherthantype();
    }

    /**
     * Create an instance of {@link Actortypes }
     * 
     */
    public Actortypes createActortypes() {
        return new Actortypes();
    }

    /**
     * Create an instance of {@link Mobilitytypes }
     * 
     */
    public Mobilitytypes createMobilitytypes() {
        return new Mobilitytypes();
    }

    /**
     * Create an instance of {@link Lowerthantype }
     * 
     */
    public Lowerthantype createLowerthantype() {
        return new Lowerthantype();
    }

    /**
     * Create an instance of {@link Schemestype.Notsupported }
     * 
     */
    public Schemestype.Notsupported createSchemestypeNotsupported() {
        return new Schemestype.Notsupported();
    }

    /**
     * Create an instance of {@link Actortype }
     * 
     */
    public Actortype createActortype() {
        return new Actortype();
    }

    /**
     * Create an instance of {@link Duplextypes }
     * 
     */
    public Duplextypes createDuplextypes() {
        return new Duplextypes();
    }

    /**
     * Create an instance of {@link Schemestype.Supported }
     * 
     */
    public Schemestype.Supported createSchemestypeSupported() {
        return new Schemestype.Supported();
    }

    /**
     * Create an instance of {@link Duplextype }
     * 
     */
    public Duplextype createDuplextype() {
        return new Duplextype();
    }

    /**
     * Create an instance of {@link Servcapstype }
     * 
     */
    public Servcapstype createServcapstype() {
        return new Servcapstype();
    }

    /**
     * Create an instance of {@link Languagestype }
     * 
     */
    public Languagestype createLanguagestype() {
        return new Languagestype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Servcapstype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:pidf:caps", name = "servcaps")
    public JAXBElement<Servcapstype> createServcaps(Servcapstype value) {
        return new JAXBElement<Servcapstype>(_Servcaps_QNAME, Servcapstype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Devcaps }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:pidf:caps", name = "devcaps")
    public JAXBElement<Devcaps> createDevcaps(Devcaps value) {
        return new JAXBElement<Devcaps>(_Devcaps_QNAME, Devcaps.class, null, value);
    }

}
