/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 03:36:58 AM WET 
//


package org.mobicents.slee.sippresence.pojo.pidf.uacaps;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for prioritytypes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prioritytypes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="equals" type="{urn:ietf:params:xml:ns:pidf:caps}equalstype" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="higherhan" type="{urn:ietf:params:xml:ns:pidf:caps}higherthantype" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lowerthan" type="{urn:ietf:params:xml:ns:pidf:caps}lowerthantype" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="range" type="{urn:ietf:params:xml:ns:pidf:caps}rangetype" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prioritytypes", propOrder = {
    "equals",
    "higherhan",
    "lowerthan",
    "range",
    "any"
})
public class Prioritytypes {

    protected List<Equalstype> equals;
    protected List<Higherthantype> higherhan;
    protected List<Lowerthantype> lowerthan;
    protected List<Rangetype> range;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the equals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquals().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Equalstype }
     * 
     * 
     */
    public List<Equalstype> getEquals() {
        if (equals == null) {
            equals = new ArrayList<Equalstype>();
        }
        return this.equals;
    }

    /**
     * Gets the value of the higherhan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the higherhan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHigherhan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Higherthantype }
     * 
     * 
     */
    public List<Higherthantype> getHigherhan() {
        if (higherhan == null) {
            higherhan = new ArrayList<Higherthantype>();
        }
        return this.higherhan;
    }

    /**
     * Gets the value of the lowerthan property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lowerthan property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLowerthan().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lowerthantype }
     * 
     * 
     */
    public List<Lowerthantype> getLowerthan() {
        if (lowerthan == null) {
            lowerthan = new ArrayList<Lowerthantype>();
        }
        return this.lowerthan;
    }

    /**
     * Gets the value of the range property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the range property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rangetype }
     * 
     * 
     */
    public List<Rangetype> getRange() {
        if (range == null) {
            range = new ArrayList<Rangetype>();
        }
        return this.range;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
