/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 03:36:58 AM WET 
//


package org.mobicents.slee.sippresence.pojo.pidf.uacaps;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for servcapstype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="servcapstype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actor" type="{urn:ietf:params:xml:ns:pidf:caps}actortype" minOccurs="0"/>
 *         &lt;element name="application" type="{urn:ietf:params:xml:ns:pidf:caps}applicationtype" minOccurs="0"/>
 *         &lt;element name="audio" type="{urn:ietf:params:xml:ns:pidf:caps}audiotype" minOccurs="0"/>
 *         &lt;element name="automata" type="{urn:ietf:params:xml:ns:pidf:caps}automatatype" minOccurs="0"/>
 *         &lt;element name="class" type="{urn:ietf:params:xml:ns:pidf:caps}classtype" minOccurs="0"/>
 *         &lt;element name="control" type="{urn:ietf:params:xml:ns:pidf:caps}controltype" minOccurs="0"/>
 *         &lt;element name="data" type="{urn:ietf:params:xml:ns:pidf:caps}datatype" minOccurs="0"/>
 *         &lt;element name="description" type="{urn:ietf:params:xml:ns:pidf:caps}descriptiontype" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="duplex" type="{urn:ietf:params:xml:ns:pidf:caps}duplextype" minOccurs="0"/>
 *         &lt;element name="event-packages" type="{urn:ietf:params:xml:ns:pidf:caps}event-packagestype" minOccurs="0"/>
 *         &lt;element name="extensions" type="{urn:ietf:params:xml:ns:pidf:caps}extensionstype" minOccurs="0"/>
 *         &lt;element name="isfocus" type="{urn:ietf:params:xml:ns:pidf:caps}isfocustype" minOccurs="0"/>
 *         &lt;element name="message" type="{urn:ietf:params:xml:ns:pidf:caps}messagetype" minOccurs="0"/>
 *         &lt;element name="methods" type="{urn:ietf:params:xml:ns:pidf:caps}methodstype" minOccurs="0"/>
 *         &lt;element name="languages" type="{urn:ietf:params:xml:ns:pidf:caps}languagestype" minOccurs="0"/>
 *         &lt;element name="priority" type="{urn:ietf:params:xml:ns:pidf:caps}prioritytype" minOccurs="0"/>
 *         &lt;element name="schemes" type="{urn:ietf:params:xml:ns:pidf:caps}schemestype" minOccurs="0"/>
 *         &lt;element name="text" type="{urn:ietf:params:xml:ns:pidf:caps}texttype" minOccurs="0"/>
 *         &lt;element name="type" type="{urn:ietf:params:xml:ns:pidf:caps}typetype" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="video" type="{urn:ietf:params:xml:ns:pidf:caps}videotype" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "servcapstype", propOrder = {
    "actor",
    "application",
    "audio",
    "automata",
    "clazz",
    "control",
    "data",
    "description",
    "duplex",
    "eventPackages",
    "extensions",
    "isfocus",
    "message",
    "methods",
    "languages",
    "priority",
    "schemes",
    "text",
    "type",
    "video",
    "any"
})
public class Servcapstype {

    protected Actortype actor;
    protected Boolean application;
    protected Boolean audio;
    protected Boolean automata;
    @XmlElement(name = "class")
    protected Classtype clazz;
    protected Boolean control;
    protected Boolean data;
    protected List<Descriptiontype> description;
    protected Duplextype duplex;
    @XmlElement(name = "event-packages")
    protected EventPackagestype eventPackages;
    protected Extensionstype extensions;
    protected Boolean isfocus;
    protected Boolean message;
    protected Methodstype methods;
    protected Languagestype languages;
    protected Prioritytype priority;
    protected Schemestype schemes;
    protected Boolean text;
    protected List<String> type;
    protected Boolean video;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the actor property.
     * 
     * @return
     *     possible object is
     *     {@link Actortype }
     *     
     */
    public Actortype getActor() {
        return actor;
    }

    /**
     * Sets the value of the actor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actortype }
     *     
     */
    public void setActor(Actortype value) {
        this.actor = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApplication(Boolean value) {
        this.application = value;
    }

    /**
     * Gets the value of the audio property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAudio() {
        return audio;
    }

    /**
     * Sets the value of the audio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAudio(Boolean value) {
        this.audio = value;
    }

    /**
     * Gets the value of the automata property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAutomata() {
        return automata;
    }

    /**
     * Sets the value of the automata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutomata(Boolean value) {
        this.automata = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link Classtype }
     *     
     */
    public Classtype getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classtype }
     *     
     */
    public void setClazz(Classtype value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the control property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isControl() {
        return control;
    }

    /**
     * Sets the value of the control property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setControl(Boolean value) {
        this.control = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setData(Boolean value) {
        this.data = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Descriptiontype }
     * 
     * 
     */
    public List<Descriptiontype> getDescription() {
        if (description == null) {
            description = new ArrayList<Descriptiontype>();
        }
        return this.description;
    }

    /**
     * Gets the value of the duplex property.
     * 
     * @return
     *     possible object is
     *     {@link Duplextype }
     *     
     */
    public Duplextype getDuplex() {
        return duplex;
    }

    /**
     * Sets the value of the duplex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duplextype }
     *     
     */
    public void setDuplex(Duplextype value) {
        this.duplex = value;
    }

    /**
     * Gets the value of the eventPackages property.
     * 
     * @return
     *     possible object is
     *     {@link EventPackagestype }
     *     
     */
    public EventPackagestype getEventPackages() {
        return eventPackages;
    }

    /**
     * Sets the value of the eventPackages property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventPackagestype }
     *     
     */
    public void setEventPackages(EventPackagestype value) {
        this.eventPackages = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensionstype }
     *     
     */
    public Extensionstype getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensionstype }
     *     
     */
    public void setExtensions(Extensionstype value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the isfocus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsfocus() {
        return isfocus;
    }

    /**
     * Sets the value of the isfocus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsfocus(Boolean value) {
        this.isfocus = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMessage(Boolean value) {
        this.message = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return
     *     possible object is
     *     {@link Methodstype }
     *     
     */
    public Methodstype getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value
     *     allowed object is
     *     {@link Methodstype }
     *     
     */
    public void setMethods(Methodstype value) {
        this.methods = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link Languagestype }
     *     
     */
    public Languagestype getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Languagestype }
     *     
     */
    public void setLanguages(Languagestype value) {
        this.languages = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Prioritytype }
     *     
     */
    public Prioritytype getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prioritytype }
     *     
     */
    public void setPriority(Prioritytype value) {
        this.priority = value;
    }

    /**
     * Gets the value of the schemes property.
     * 
     * @return
     *     possible object is
     *     {@link Schemestype }
     *     
     */
    public Schemestype getSchemes() {
        return schemes;
    }

    /**
     * Sets the value of the schemes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schemestype }
     *     
     */
    public void setSchemes(Schemestype value) {
        this.schemes = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setText(Boolean value) {
        this.text = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getType() {
        if (type == null) {
            type = new ArrayList<String>();
        }
        return this.type;
    }

    /**
     * Gets the value of the video property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVideo() {
        return video;
    }

    /**
     * Sets the value of the video property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVideo(Boolean value) {
        this.video = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
