package org.mobicents.slee.sipevent.server.subscription;


public interface SubscriptionControlSbbLocalObject extends
		SubscriptionControl,ImplementedSubscriptionControlParentSbbLocalObject,
		SubscriptionClientControlSbbLocalObject,EventListSubscriptionControlParentSbbLocalObject {

}
