/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.01 at 05:19:28 PM WEST 
//


package org.mobicents.slee.sippresence.pojo.xcaperror;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ietf:params:xml:ns:xcap-error}error-element"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "errorElement"
})
@XmlRootElement(name = "xcap-error")
public class XcapError {

    @XmlElementRef(name = "error-element", namespace = "urn:ietf:params:xml:ns:xcap-error", type = JAXBElement.class)
    protected JAXBElement<?> errorElement;

    /**
     * Gets the value of the errorElement property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CannotInsert }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link NotUtf8 }{@code >}
     *     {@link JAXBElement }{@code <}{@link NotWellFormed }{@code >}
     *     {@link JAXBElement }{@code <}{@link UniquenessFailure }{@code >}
     *     {@link JAXBElement }{@code <}{@link CannotDelete }{@code >}
     *     {@link JAXBElement }{@code <}{@link NotXmlFrag }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConstraintFailure }{@code >}
     *     {@link JAXBElement }{@code <}{@link NoParent }{@code >}
     *     {@link JAXBElement }{@code <}{@link SchemaValidationError }{@code >}
     *     {@link JAXBElement }{@code <}{@link NotXmlAttValue }{@code >}
     *     
     */
    public JAXBElement<?> getErrorElement() {
        return errorElement;
    }

    /**
     * Sets the value of the errorElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CannotInsert }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link NotUtf8 }{@code >}
     *     {@link JAXBElement }{@code <}{@link NotWellFormed }{@code >}
     *     {@link JAXBElement }{@code <}{@link UniquenessFailure }{@code >}
     *     {@link JAXBElement }{@code <}{@link CannotDelete }{@code >}
     *     {@link JAXBElement }{@code <}{@link NotXmlFrag }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConstraintFailure }{@code >}
     *     {@link JAXBElement }{@code <}{@link NoParent }{@code >}
     *     {@link JAXBElement }{@code <}{@link SchemaValidationError }{@code >}
     *     {@link JAXBElement }{@code <}{@link NotXmlAttValue }{@code >}
     *     
     */
    public void setErrorElement(JAXBElement<?> value) {
        this.errorElement = ((JAXBElement<?> ) value);
    }

}
