/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 03:36:58 AM WET 
//


package org.mobicents.slee.sippresence.pojo.pidf.geopriv10;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mobicents.slee.sippresence.pojo.pidf.geopriv10.basicPolicy.LocPolicyType;
import org.w3c.dom.Element;


/**
 * <p>Java class for geopriv complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="geopriv">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="location-info" type="{urn:ietf:params:xml:ns:pidf:geopriv10}locInfoType"/>
 *         &lt;element name="usage-rules" type="{urn:ietf:params:xml:ns:pidf:geopriv10:basicPolicy}locPolicyType"/>
 *         &lt;element name="method" type="{urn:ietf:params:xml:ns:pidf:geopriv10}locMethod" minOccurs="0"/>
 *         &lt;element name="provided-by" type="{urn:ietf:params:xml:ns:pidf:geopriv10}locProvidedBy" minOccurs="0"/>
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "geopriv", propOrder = {
    "locationInfo",
    "usageRules",
    "method",
    "providedBy",
    "any"
})
public class Geopriv {

    @XmlElement(name = "location-info", required = true)
    protected LocInfoType locationInfo;
    @XmlElement(name = "usage-rules", required = true)
    protected LocPolicyType usageRules;
    protected LocMethod method;
    @XmlElement(name = "provided-by")
    protected LocProvidedBy providedBy;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the locationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LocInfoType }
     *     
     */
    public LocInfoType getLocationInfo() {
        return locationInfo;
    }

    /**
     * Sets the value of the locationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocInfoType }
     *     
     */
    public void setLocationInfo(LocInfoType value) {
        this.locationInfo = value;
    }

    /**
     * Gets the value of the usageRules property.
     * 
     * @return
     *     possible object is
     *     {@link LocPolicyType }
     *     
     */
    public LocPolicyType getUsageRules() {
        return usageRules;
    }

    /**
     * Sets the value of the usageRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocPolicyType }
     *     
     */
    public void setUsageRules(LocPolicyType value) {
        this.usageRules = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link LocMethod }
     *     
     */
    public LocMethod getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocMethod }
     *     
     */
    public void setMethod(LocMethod value) {
        this.method = value;
    }

    /**
     * Gets the value of the providedBy property.
     * 
     * @return
     *     possible object is
     *     {@link LocProvidedBy }
     *     
     */
    public LocProvidedBy getProvidedBy() {
        return providedBy;
    }

    /**
     * Sets the value of the providedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocProvidedBy }
     *     
     */
    public void setProvidedBy(LocProvidedBy value) {
        this.providedBy = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
