/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and individual contributors
 * by the @authors tag. See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.01 at 05:17:03 PM WEST 
//


package org.openxdm.xcap.client.appusage.resourcelists.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openxdm.xcap.client.appusage.resourcelists.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListTypeEntryRef_QNAME = new QName("urn:ietf:params:xml:ns:resource-lists", "entry-ref");
    private final static QName _ListTypeList_QNAME = new QName("urn:ietf:params:xml:ns:resource-lists", "list");
    private final static QName _ListTypeEntry_QNAME = new QName("urn:ietf:params:xml:ns:resource-lists", "entry");
    private final static QName _ListTypeExternal_QNAME = new QName("urn:ietf:params:xml:ns:resource-lists", "external");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openxdm.xcap.client.appusage.resourcelists.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListType.List }
     * 
     */
    public ListType.List createListTypeList() {
        return new ListType.List();
    }

    /**
     * Create an instance of {@link DisplayNameType }
     * 
     */
    public DisplayNameType createDisplayNameType() {
        return new DisplayNameType();
    }

    /**
     * Create an instance of {@link ResourceLists }
     * 
     */
    public ResourceLists createResourceLists() {
        return new ResourceLists();
    }

    /**
     * Create an instance of {@link EntryRefType }
     * 
     */
    public EntryRefType createEntryRefType() {
        return new EntryRefType();
    }

    /**
     * Create an instance of {@link ExternalType }
     * 
     */
    public ExternalType createExternalType() {
        return new ExternalType();
    }

    /**
     * Create an instance of {@link EntryType.DisplayName }
     * 
     */
    public EntryType.DisplayName createEntryTypeDisplayName() {
        return new EntryType.DisplayName();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntryRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:resource-lists", name = "entry-ref", scope = ListType.class)
    public JAXBElement<EntryRefType> createListTypeEntryRef(EntryRefType value) {
        return new JAXBElement<EntryRefType>(_ListTypeEntryRef_QNAME, EntryRefType.class, ListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListType.List }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:resource-lists", name = "list", scope = ListType.class)
    public JAXBElement<ListType.List> createListTypeList(ListType.List value) {
        return new JAXBElement<ListType.List>(_ListTypeList_QNAME, ListType.List.class, ListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:resource-lists", name = "entry", scope = ListType.class)
    public JAXBElement<EntryType> createListTypeEntry(EntryType value) {
        return new JAXBElement<EntryType>(_ListTypeEntry_QNAME, EntryType.class, ListType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ietf:params:xml:ns:resource-lists", name = "external", scope = ListType.class)
    public JAXBElement<ExternalType> createListTypeExternal(ExternalType value) {
        return new JAXBElement<ExternalType>(_ListTypeExternal_QNAME, ExternalType.class, ListType.class, value);
    }

}
